# Steps:
#   1. open Windows Powershell (as admin??)
#   2. cd to the directory that this file is located in
#   3. run the following command:
#        docker build -t docker_boyd.txt .

# Notes and changes:
# 1. The initial run generated this warning:
#    debconf: delaying package configuration, since apt-utils is not installed
#      however, it must have installed apt-utils as this did not occur on the second run
# 2. I have replaced empty lines after RUN below with commented lines as emtpty continuation lines may
#      be an error in future docker releases
# 3. I got this error:
#    COPY failed: stat /var/lib/docker/tmp/docker-builder539867021/coinhsl-2019.05.21: no such file or directory
#    I commented it out


FROM python:3

RUN echo "$USER ALL = NOPASSWD: ALL" >> /etc/sudoers && \
#  
    apt-get update && apt-get install -y \
        gcc g++ gfortran git patch wget pkg-config liblapack-dev libmetis-dev
# 
# COPY coinhsl-2019.05.21 /tmp/coinhsl-2019.05.21/ 
ADD test_cyipopt.py /
ADD get_ipopt.sh /tmp/
ADD get_cyipopt.sh /tmp/
RUN bash /tmp/get_ipopt.sh
ENV IPOPTPATH /opt/ipopt
ENV PKG_CONFIG_PATH $PKG_CONFIG_PATH:$IPOPTPATH/lib/pkgconfig
ENV PATH $PATH:$IPOPTPATH/bin
RUN bash --login /tmp/get_cyipopt.sh
RUN rm /tmp/get_ipopt.sh /tmp/get_cyipopt.sh

CMD [ "python", "./test_cyipopt.py" ]